id = "rose-pine-theme"
name = "Rosé Pine"
version = "1.0.9"
schema_version = 1
authors = ["Kainoa Kanter <kainoa@t1c.dev>"]
description = "All natural pine, faux fur, and a bit of soho vibes – a classy minimalist theme for Zed."
repository = "https://github.com/rose-pine/zed"
